# Generated by Django 4.2.1 on 2023-05-14 16:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('photos', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='comment',
            name='photo',
        ),
        migrations.AddField(
            model_name='comment',
            name='album',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, to='photos.album'),
            preserve_default=False,
        ),
    ]
